version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - install
      - server
    links:
      - server
    ports:
      - "8080:80"
    networks:
      - internal
    env_file:
      - sys.env
    volumes:
      - ./:/www/
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    env_file:
      - sys.env
    networks:
      - internal
  install:
    image: linojobs/php
    container_name: install
    restart: "no"
    env_file:
      - sys.env
    depends_on:
      - mariadb
    links:
      - mariadb
    networks:
      - internal
    volumes:
      - ./installer/:/installer/
    command: [ "/usr/local/php/bin/php", "/installer/install.php" ]
  entry:
    build: ./packages/admin-entry
    container_name: entry
    volumes:
      - ./:/admin-studio/
    env_file:
      - sys.env
  server:
    build: ./packages/admin-server
    container_name: server
    restart: always
    env_file:
      - sys.env
    depends_on:
      - mariadb
      - install
    links:
      - mariadb
    networks:
      - internal
    volumes:
      - ./:/admin-studio/
networks:
  internal:
    driver: bridge
