version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    depends_on:
      - install
      - nodejs
    links:
      - nodejs
    ports:
      - "8080:80"
    env_file:
      - sys.env
    networks:
      - internal
    volumes:
      - ./:/www/
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - internal
    env_file:
      - sys.env
  nodejs:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nodejs
    restart: always
    env_file:
      - sys.env
    depends_on:
      - mariadb
      - install
    links:
      - mariadb
    networks:
      - internal
    volumes:
      - ./server/:/server/
  install:
    image: linojobs/php
    container_name: install
    restart: "no"
    env_file:
      - sys.env
    depends_on:
      - mariadb
    networks:
      - internal
    volumes:
      - ./installer/:/installer/
    command: [ "/usr/local/php/bin/php", "/installer/install.php" ]
networks:
  internal:
    driver: bridge
