version: "3"
services:
  store:
    build: ./packages/admin-store
    container_name: store
    networks:
      - internal
    volumes:
      - ./:/admin-studio/
    env_file:
      - ./web.env
  ui:
    build: ./packages/admin-ui
    container_name: ui
    networks:
      - internal
    volumes:
      - ./:/admin-studio/
    env_file:
      - ./web.env
  ide:
    build: ./packages/admin-ide
    container_name: ide
    networks:
      - internal
    volumes:
      - ./:/admin-studio/
    env_file:
      - ./web.env
  server:
    build: ./packages/admin-server
    container_name: server
    networks:
      - internal
    volumes:
      - ./:/admin-studio/
    env_file:
      - ./web.env
networks:
  internal:
    driver: bridge
